services:
  db:
    image: "postgres:14.15-alpine"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 2

  cotrip-backend:
    image: "younesadem/cotrip-backend:latest"
    environment:
      - DB_URL=jdbc:postgresql://db:5432/${POSTGRES_DB}
      - DB_USERNAME=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"

  cotrip-frontend:
    image: "younesadem/cotrip-frontend:latest"
    depends_on:
      cotrip-backend:
        condition: service_started
    ports:
      - "5173:5173"

volumes:
  postgres_data:
